### ISSUE TITLE
getting exceptions while applying amps.

### ISSUE THREAD

**Issue by monicakumari** [Redpill-Linpro/alfresco-s3-adapter#2]
Hello,

I just created amps for this project and applies to a vanila installation. I got the below exception
[exception.txt](https://github.com/Redpill-Linpro/alfresco-s3-adapter/files/2102267/exception.txt)

**Comment by monicakumari** [comment]
I have created a new project and copied all the files and bean ids and it was working fine. standalone, its working but with the vanila installation I am getting the above mentioned exception.

Please help me in understanding why this is happening and what should I do to make it work.

Thanks.

**Comment by MarkTielemans** [comment]
It seems that Apache HttpClient is either missing or has an incompatible version available at runtime. Try including the correct Apache HttpClient version as a dependency in your project.

**Comment by monicakumari** [comment]
Thank you for your response. what should be the version for the same ? Or I'll google it for the latest version.

thanks.

**Comment by MarkTielemans** [comment]
Any version that has a matching constructor for `org.apache.http.conn.ssl.SSLConnectionSocketFactory.<init>(Ljavax/net/ssl/SSLContext;Ljavax/net/ssl/HostnameVerifier;)`

This seems to be an option:
```
<dependency>
  <groupId>org.apache.httpcomponents</groupId>
  <artifactId>httpclient</artifactId>
  <version>4.5.2</version>
</dependency>
```

**Comment by monicakumari** [comment]
Thank you Mark. I have tried this as well as 
`<dependency>
  <groupId>org.apache.httpcomponents</groupId>
  <artifactId>httpclient</artifactId>
  <version>4.5.5</version>
</dependency>`
but getting the same exception. I have no idea what to do now.

**Comment by monicakumari** [comment]
Also, I have checked installation's WEB-INF/lib for apache http client. it was 4.5.2. 
after that I have added the 4.5.2 version and applied it. also tested it for version 4.5.5. still getting the same exceptions.

**Comment by monicakumari** [comment]
Hello, 

after using 4.5.5, I am getting another exception.

> Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org.apache.http.impl.conn.CPool.setValidateAfterInactivity(I)V

**Comment by monicakumari** [comment]
Hello Mark,

I have updated the httpclient and httpcore jars to the latest version, now the tomcat started but not connected with the s3. I have enabled the log and got a new exception :- 

> 2018-06-27 12:23:15,930  ERROR [audit.model.AuditModelRegistryImpl] [localhost-startStop-1] Failed to load audit model: jar:file:/opt/alfresco/aws_test/tomcat/webapps/alfresco/WEB-INF/lib/alfresco-repository-5.2.g.jar!/alfresco/audit/alfresco-audit-tagging.xml
>  org.alfresco.service.cmr.repository.ContentIOException: 05270001 Failed to open stream onto channel: 
>    writer: ContentAccessor[ contentUrl=store://2018/6/27/12/23/c0d3ab4e-2426-405b-8b84-ce64bde3a314.bin, mimetype=text/xml, size=0, encoding=UTF-8, locale=en_IN]
> 	at org.alfresco.repo.content.AbstractContentWriter.getContentOutputStream(AbstractContentWriter.java:436)
> 	at org.alfresco.repo.content.AbstractContentWriter.putContent(AbstractContentWriter.java:468)
> 

Please advice.

Thanks.

**Comment by monicakumari** [comment]
resolved this. there was an access issue with /tmp/cachecontent folder. deleted everything inside /tmp/ and it worked.
